crud/urls.py
from . import views
from django.conf.urls import url
from django.urls import path

app_name = 'crud'

urlpatterns = [
    # Create a new register
    url(r'newp/', views.ProjetosCreate.as_view(), name='form_projs'),
    url(r'newc/', views.ComponentesCreate.as_view(), name='form_comps'),
    url(r'newt/', views.TecnologiasCreate.as_view(), name='form_techs'),
    url(r'newu/', views.UsuariosCreate.as_view(), name='form_users'),

    # Update an existent register
    path(r'editp/<int:pk>', views.ProjetosUpdate.as_view(), name='form_projs'),
    path(r'editc/<int:pk>', views.ComponentesUpdate.as_view(), name='form_comps'),
    path(r'editt/<int:pk>', views.TecnologiasUpdate.as_view(), name='form_techs'),
    path(r'editu/<int:pk>', views.UsuariosUpdate.as_view(), name='form_users'),

    # Delete an existent register
    path(r'delep/<int:pk>', views.ProjetosDelete.as_view(), name='dele_projs'),
    path(r'delec/<int:pk>', views.ComponentesDelete.as_view(), name='dele_comps'),
    path(r'delet/<int:pk>', views.TecnologiasDelete.as_view(), name='dele_techs'),
    path(r'deleu/<int:pk>', views.UsuariosDelete.as_view(), name='dele_users'),

    # Detail of an existent register
    path(r'viewp/<int:pk>', views.ProjetosView.as_view(), name='view_projs'),
    path(r'viewc/<int:pk>', views.ComponentesView.as_view(), name='view_comps'),
    path(r'viewt/<int:pk>', views.TecnologiasView.as_view(), name='view_techs'),
    path(r'viewu/<int:pk>', views.UsuariosView.as_view(), name='view_users'),
]

sistema/urls.py
from . import views
from django.conf.urls import url

app_name = 'sistema'

urlpatterns = [
    url(r'base', views.base, name='base'),
    url(r'based/', views.based, name='based'),
    url(r'blank/', views.blank, name='blank'),
    url(r'charts/', views.charts, name='charts'),
    url(r'error404/', views.error404, name='error404'),
    url(r'^$', views.index, name='index'),
    url(r'tables/', views.tables, name='tables'),

    url(r'channels/', views.channels, name='channels'),
    url(r'publics/', views.publics, name='publics'),
    url(r'watcheds/', views.watcheds, name='watcheds'),

    url(r'accessibility/', views.accessibility, name='accessibility'),
    url(r'acquisition/', views.acquisition, name='acquisition'),
    url(r'file_upload/', views.file_upload, name='file_upload'),
    url(r'data_upload/', views.data_upload, name='data_upload'),
    url(r'read_files/', views.read_files, name='read_files'),
    url(r'storage/', views.storage, name='storage'),
    url(r'synchronization/', views.synchronization, name='synchronization'),

    url(r'components/', views.components, name='components'),
    url(r'projects/', views.projects, name='projects'),
    url(r'technologies/', views.technologies, name='technologies'),
    url(r'users/', views.users, name='users'),
]

uvfriendly/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Interface administrativa
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),


    # URL padrão
    path('', include('website.urls', namespace='website')),
    path('sistema/', include('sistema.urls', namespace='sistema')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('crud/', include('crud.urls', namespace='crud')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

uvfriendly/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Document(models.Model):
    description = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to='documents/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    objetos = models.Manager()



class Componentes(models.Model):
    nome = models.CharField(
        max_length=50, null=False, blank=False)
    descricao = models.CharField(
        max_length=150, null=False, blank=False)
    fullsize = models.CharField(
        max_length=255, null=False, blank=False)
    thumbnails = models.CharField(
        max_length=255, null=False, blank=False)
    status = models.IntegerField(
        null=False, blank=False, default=0)

    objetos = models.Manager()


class Projetos(models.Model):
    nome = models.CharField(
        max_length=20, null=False, blank=False)
    descricao = models.CharField(
        max_length=255, null=False, blank=False)
    classe = models.CharField(
        max_length=255, null=False, blank=False, default='')
    status = models.IntegerField(
        null=False, blank=False, default=0)

    objetos = models.Manager()


class Tecnologias(models.Model):
    classe = models.CharField(
        max_length=150, null=False, blank=False)
    alt = models.CharField(
        max_length=50, null=False, blank=False)
    nome = models.CharField(
        max_length=50, null=False, blank=False)
    status = models.IntegerField(
        null=False, blank=False, default=0)

    objetos = models.Manager()


class Usuarios(models.Model):
    cpf = models.CharField(
        max_length=14, null=False, blank=False)
    nome = models.CharField(
        max_length=255, null=False, blank=False)
    sobrenome = models.CharField(
        max_length=255, null=False, blank=False)
    email = models.EmailField(
        max_length=255, null=False, blank=False)
    senha1 = models.CharField(
        max_length=255, null=False, blank=False)
    senha2 = models.CharField(
        max_length=255, null=False, blank=False)
    status = models.IntegerField(
        default=0, null=False, blank=False)
    level = models.IntegerField(
        default=0, null=False, blank=False)

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse('form_users', kwargs={'pk':self.pk})

    objetos = models.Manager()


class Canais(models.Model):
    nome = models.ForeignKey(Usuarios, on_delete=models.CASCADE)
    nomecanal = models.CharField(
        max_length=50, null=False, blank=False)
    descricao = models.CharField(
        max_length=150, null=False, blank=False)
    campo_01 = models.CharField(
        max_length=50, null=True, blank=True)
    campo_02 = models.CharField(
        max_length=50, null=True, blank=True)
    campo_03 = models.CharField(
        max_length=50, null=True, blank=True)
    campo_04 = models.CharField(
        max_length=50, null=True, blank=True)
    campo_05 = models.CharField(
        max_length=50, null=True, blank=True)
    campo_06 = models.CharField(
        max_length=50, null=True, blank=True)
    campo_07 = models.CharField(
        max_length=50, null=True, blank=True)
    campo_08 = models.CharField(
        max_length=50, null=True, blank=True)
    metadata = models.CharField(
        max_length=255, null=False, blank=False)
    tags = models.CharField(
        max_length=255, null=False, blank=False)
    latitude = models.IntegerField(
        null=True, blank=True, default=0)
    longitude = models.IntegerField(
        null=True, blank=True, default=0)
    elevation = models.IntegerField(
        null=True, blank=True, default=0)
    status = models.IntegerField(
        null=True, blank=True, default=0)

    objetos = models.Manager()

sistema/views.py
from django.core.files.storage import FileSystemStorage
from django.shortcuts import render, redirect
from matplotlib import pyplot as plt
import pandas as pd

from uvfriendly.models import Componentes, Projetos, Tecnologias, Usuarios
from uvfriendly.forms import DocumentForm

template_name = 'sistema'

# Create your views here.
def base(request):
    return render(request, 'sistema/base.html')


def based(request):
    return render(request, 'sistema/based.html')


def blank(request):
    return render(request, 'sistema/blank.html')


def charts(request):
    return render(request, 'sistema/charts.html')


def error404(request):
    return render(request, 'sistema/error404.html')


def index(request):
    return render(request, 'sistema/index.html')


def tables(request):
    tabela = pd.read_csv("media/documents/german_credit.csv")
    contexto = {
        'tabela': tabela.to_html(index=False)
    }
    return render(request, 'sistema/tables.html', contexto)

#====================================================

# Channels ===================================================
def channels(request):
    return render(request, 'sistema/channels/channels.html')


def publics(request):
    return render(request, 'sistema/channels/publics.html')


def watcheds(request):
    return render(request, 'sistema/channels/watcheds.html')

#=============================================================

# Tasks ==========================================================
def accessibility(request):
    return render(request, 'sistema/tasks/accessibility.html')


def acquisition(request):
    return render(request, 'sistema/tasks/acquisition.html')


def storage(request):
    return render(request, 'sistema/tasks/storage.html')


def synchronization(request):
    return render(request, 'sistema/tasks/synchronization.html')

#=================================================================

# Tools ===================================================================================
def components(request):
    componentes = Componentes.objetos.all()
    contexto = {
        'componentes': componentes
    }
    return render(request, 'sistema/tools/components.html', contexto)

#__________________________________________________________________________________________
def projects(request):
    projetos = Projetos.objetos.all()
    contexto = {
        'projetos': projetos
    }
    return render(request, 'sistema/tools/projects.html', contexto)

#_______________________________________________________________________________________________________________________
def technologies(request):
    tecnologias = Tecnologias.objetos.all()
    contexto = {
        'tecnologias': tecnologias
    }
    return render(request, 'sistema/tools/technologies.html', contexto)

#_______________________________________________________________________________________________________________________
def users(request):
    usuarios = Usuarios.objetos.all()
    contexto = {
        'usuarios':usuarios
    }
    return render(request, 'sistema/tools/users.html', contexto)

#=======================================================================================================================
def file_upload(request):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)
        return render(request, 'sistema/tasks/file_upload.html',{
            'uploaded_file_url': uploaded_file_url
        })
    return render(request, 'sistema/tasks/file_upload.html')

#=======================================================================================================================
def data_upload(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('sistema/tasks/data_upload.html')
    else:
        form = DocumentForm()
    return render(request, 'sistema/tasks/data_upload.html', {
        'form': form
    })

#=======================================================================================================================
def read_files(request):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        # myfile = "media/documents/german_credit.csv"
        # df = pd.DataFrame()
        df = pd.read_csv(myfile, sep=",")
        data1 = df.iloc[1000:2136,2]
        plt.plot(data1, label='tempearatura')
        plt.title("Temperatura")
        plt.xlabel("Quantidade de Amostras")
        plt.ylabel("Temperatura em Graus Celsius")
        show1 = plt.show()
        data2 = df.iloc[1000:2136, 3]
        plt.plot(data2, label='umidade')
        plt.title("Umidade")
        plt.xlabel("Quantidade de Amostras")
        plt.ylabel("Umidade Relativa do Ar em %")
        show2 = plt.show()
        df = df.iloc[1000:2136,[0,1,2,3]]
        contexto = {
            'df': df.to_html(index=False),
            'show1': show1,
            'show2': show2,
        }
        return render(request, 'sistema/tasks/read_files.html', contexto)
    return render(request, 'sistema/tasks/read_files.html')

sistema/templates/sistema/tasks/accessibility.html
        {% extends 'sistema/base.html' %}
        <!-- template main of accessibility -->
        {% block content %}
                <li class="breadcrumb-item">Tarefas</li>
            </ol>
            <!-- Page Content -->
            <h1>Acessibilidade aos Dados</h1>
            <hr>
            <p>
                <form method="post" enctype="multipart/form-data" action="{% url 'sistema:read_files' %}">
                    {% csrf_token %}
                    <input type="file" name="myfile" accept=".csv" value="media/" required="required"><br><br>
                    <button class="btn btn-primary js-scroll-trigger" type="submit">Carregar Arquivo</button>
                </form>
            </p>
        {% endblock %}

sistema/templates/sistema/tasks/acquisition.html
        {% extends 'sistema/base.html' %}
        <!-- template main of acquisition -->
        {% block content %}
                <li class="breadcrumb-item">Tarefas</li>
            </ol>
            <!-- Page Content -->
            <h1>Aquisição de Dados</h1>
            <hr>
            <p>
                <div class="card-header mb-3"><a class="btn btn-primary js-scroll-trigger" href="{% url 'sistema:file_upload' %}"><i class="fas fa-file-upload"></i></a>&nbsp;&nbsp;Upload de Arquivos para o Sistema de Arquivos</div>
                <div class="card-header mb-3"><a class="btn btn-primary js-scroll-trigger" href="{% url 'sistema:data_upload' %}"><i class="fas fa-database"></i></a>&nbsp;&nbsp;Upload de Arquivos para o Banco de Dados</div>
            </p>
        {% endblock %}

sistema/templates/sistema/tasks/data_upload.html
        {% extends 'sistema/base.html' %}
        <!-- template of data_upload -->
        {% block content %}
                <li class="breadcrumb-item">Tarefas</li>
            </ol>
            <!-- Page Content -->
            <h1>Upload de Arquivos para o Banco de Dados</h1>
            <hr>
            <p>
                <a class="btn btn-primary js-scroll-trigger" href="{% url 'sistema:acquisition' %}"><i class="fas fa-undo-alt"></i></a>
            </p>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <div class="">
                        <label for="id_description">Descrição:</label>
                        <input type="text" name="description" id="id_description" class="form-control" placeholder="Informe a descrição do Arquivo" required="required" maxlength="255" autofocus="autofocus">
                    </div>
                </div>
                <div class="form-group">
                    <div class="">
                        <label for="id_document">Arquivo:</label><br>
                        <input type="file" name="document" accept=".csv" id="id_document" required="required">
                    </div>
                </div>
                <button class="btn btn-primary js-scroll-trigger" type="submit">Upload</button>
            </form>
        {% endblock %}

sistema/templates/sistema/tasks/file_upload.html
        {% extends 'sistema/base.html' %}
        <!-- template of file_upload -->
        {% block content %}
                <li class="breadcrumb-item">Tarefas</li>
            </ol>
            <!-- Page Content -->
            <h1>Upload de Arquivos para o Sistema de Arquivos</h1>
            <hr>
            <p>
                <a class="btn btn-primary js-scroll-trigger" href="{% url 'sistema:acquisition' %}"><i class="fas fa-undo-alt"></i></a>
            </p>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="file" name="myfile" accept=".csv" required="required"><br><br>
                <button class="btn btn-primary js-scroll-trigger" type="submit">Upload</button>
            </form>
            {% if uploaded_file_url %}
                <br><p>Arquivo enviado para: {{ uploaded_file_url }}</p>
            {% endif %}
        {% endblock %}

sistema/templates/sistema/tasks/read_files.html
        {% extends 'sistema/base.html' %}
        <!-- template of read_files -->
        {% block content %}
                <li class="breadcrumb-item">Tarefas</li>
            </ol>
            <!-- Page Content -->
            <h1>Lê o arquivo pelo Pandas</h1>
            <hr>
            <p>
                <a class="btn btn-primary js-scroll-trigger" href="{% url 'sistema:accessibility' %}"><i class="fas fa-undo-alt"></i></a>
            </p>
            {% autoescape off %}
                {{ df }}
            {% endautoescape %}
        {% endblock %}

sistema/templates/sistema/tasks/storage.html
        {% extends 'sistema/base.html' %}
        <!-- template main of storage -->
        {% block content %}
            <li class="breadcrumb-item active">Tarefas</li>
          </ol>
          <!-- Page Content -->
          <h1>Armazenamento de Dados</h1>
          <hr>
          <p>
              <a class="btn btn-primary js-scroll-trigger" href="#"><i class="fas fa-plus"></i></a>
              <a class="btn btn-primary js-scroll-trigger" href="#"><i class="fas fa-edit"></i></a>
              <a class="btn btn-primary js-scroll-trigger" href="#"><i class="fas fa-trash-alt"></i></a>
              <a class="btn btn-primary js-scroll-trigger" href="#"><i class="fas fa-search"></i></a>
          </p>
        {% endblock %}

sistema/templates/sistema/tasks/synchronization.html
        {% extends 'sistema/base.html' %}
        <!-- template main of synchronization -->
        {% block content %}
            <li class="breadcrumb-item active">Tarefas</li>
          </ol>
          <!-- Page Content -->
          <h1>Sincronização dos Dados</h1>
          <hr>
          <p>
              <a class="btn btn-primary js-scroll-trigger" href="#"><i class="fas fa-plus"></i></a>
              <a class="btn btn-primary js-scroll-trigger" href="#"><i class="fas fa-edit"></i></a>
              <a class="btn btn-primary js-scroll-trigger" href="#"><i class="fas fa-trash-alt"></i></a>
              <a class="btn btn-primary js-scroll-trigger" href="#"><i class="fas fa-search"></i></a>
          </p>
        {% endblock %}