accounts/urls.py
from . import views
from django.conf.urls import url

app_name = 'accounts'

urlpatterns = [
    url(r'login/', views.login, name='login'),
    url(r'register/', views.SignUp.as_view(), name='register'),
    url(r'forgot_password/', views.forgot_password, name='forgot_password'),
]

crud/urls.py
from . import views
from django.conf.urls import url
from django.urls import path

app_name = 'crud'

urlpatterns = [
    # Create a new register
    url(r'newp/', views.ProjetosCreate.as_view(), name='form_projs'),
    url(r'newc/', views.ComponentesCreate.as_view(), name='form_comps'),
    url(r'newt/', views.TecnologiasCreate.as_view(), name='form_techs'),
    url(r'newu/', views.UsuariosCreate.as_view(), name='form_users'),

    # Update an existent register
    path(r'editp/<int:pk>', views.ProjetosUpdate.as_view(), name='form_projs'),
    path(r'editc/<int:pk>', views.ComponentesUpdate.as_view(), name='form_comps'),
    path(r'editt/<int:pk>', views.TecnologiasUpdate.as_view(), name='form_techs'),
    path(r'editu/<int:pk>', views.UsuariosUpdate.as_view(), name='form_users'),

    # Delete an existent register
    path(r'delep/<int:pk>', views.ProjetosDelete.as_view(), name='dele_projs'),
    path(r'delec/<int:pk>', views.ComponentesDelete.as_view(), name='dele_comps'),
    path(r'delet/<int:pk>', views.TecnologiasDelete.as_view(), name='dele_techs'),
    path(r'deleu/<int:pk>', views.UsuariosDelete.as_view(), name='dele_users'),

    # Detail of an existent register
    path(r'viewp/<int:pk>', views.ProjetosView.as_view(), name='view_projs'),
    path(r'viewc/<int:pk>', views.ComponentesView.as_view(), name='view_comps'),
    path(r'viewt/<int:pk>', views.TecnologiasView.as_view(), name='view_techs'),
    path(r'viewu/<int:pk>', views.UsuariosView.as_view(), name='view_users'),
]

sistema/urls.py
from . import views
from django.conf.urls import url

app_name = 'sistema'

urlpatterns = [
    url(r'base', views.base, name='base'),
    url(r'based/', views.based, name='based'),
    url(r'blank/', views.blank, name='blank'),
    url(r'charts/', views.charts, name='charts'),
    url(r'error404/', views.error404, name='error404'),
    url(r'^$', views.index, name='index'),
    url(r'tables/', views.tables, name='tables'),

    url(r'channels/', views.channels, name='channels'),
    url(r'publics/', views.publics, name='publics'),
    url(r'watcheds/', views.watcheds, name='watcheds'),

    url(r'accessibility/', views.accessibility, name='accessibility'),
    url(r'acquisition/', views.acquisition, name='acquisition'),
    url(r'file_upload/', views.file_upload, name='file_upload'),
    url(r'data_upload/', views.data_upload, name='data_upload'),
    url(r'read_files/', views.read_files, name='read_files'),
    url(r'storage/', views.storage, name='storage'),
    url(r'synchronization/', views.synchronization, name='synchronization'),

    url(r'components/', views.components, name='components'),
    url(r'projects/', views.projects, name='projects'),
    url(r'technologies/', views.technologies, name='technologies'),
    url(r'users/', views.users, name='users'),
]

uvfriendly/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Interface administrativa
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),


    # URL padrão
    path('', include('website.urls', namespace='website')),
    path('sistema/', include('sistema.urls', namespace='sistema')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('crud/', include('crud.urls', namespace='crud')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sistema/views.py
from django.core.files.storage import FileSystemStorage
from django.shortcuts import render, redirect
from matplotlib import pyplot as plt
import pandas as pd

from uvfriendly.models import Componentes, Projetos, Tecnologias, Usuarios
from uvfriendly.forms import DocumentForm

template_name = 'sistema'

# Create your views here.
def base(request):
    return render(request, 'sistema/base.html')


def based(request):
    return render(request, 'sistema/based.html')


def blank(request):
    return render(request, 'sistema/blank.html')


def charts(request):
    return render(request, 'sistema/charts.html')


def error404(request):
    return render(request, 'sistema/error404.html')


def index(request):
    return render(request, 'sistema/index.html')


def tables(request):
    tabela = pd.read_csv("media/documents/german_credit.csv")
    contexto = {
        'tabela': tabela.to_html(index=False)
    }
    return render(request, 'sistema/tables.html', contexto)

#====================================================

# Channels ===================================================
def channels(request):
    return render(request, 'sistema/channels/channels.html')


def publics(request):
    return render(request, 'sistema/channels/publics.html')


def watcheds(request):
    return render(request, 'sistema/channels/watcheds.html')

#=============================================================

# Tasks ==========================================================
def accessibility(request):
    return render(request, 'sistema/tasks/accessibility.html')


def acquisition(request):
    return render(request, 'sistema/tasks/acquisition.html')


def storage(request):
    return render(request, 'sistema/tasks/storage.html')


def synchronization(request):
    return render(request, 'sistema/tasks/synchronization.html')

#=================================================================

# Tools ===================================================================================
def components(request):
    componentes = Componentes.objetos.all()
    contexto = {
        'componentes': componentes
    }
    return render(request, 'sistema/tools/components.html', contexto)

#__________________________________________________________________________________________
def projects(request):
    projetos = Projetos.objetos.all()
    contexto = {
        'projetos': projetos
    }
    return render(request, 'sistema/tools/projects.html', contexto)

#_______________________________________________________________________________________________________________________
def technologies(request):
    tecnologias = Tecnologias.objetos.all()
    contexto = {
        'tecnologias': tecnologias
    }
    return render(request, 'sistema/tools/technologies.html', contexto)

#_______________________________________________________________________________________________________________________
def users(request):
    usuarios = Usuarios.objetos.all()
    contexto = {
        'usuarios':usuarios
    }
    return render(request, 'sistema/tools/users.html', contexto)

#=======================================================================================================================
def file_upload(request):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)
        return render(request, 'sistema/tasks/file_upload.html',{
            'uploaded_file_url': uploaded_file_url
        })
    return render(request, 'sistema/tasks/file_upload.html')

#=======================================================================================================================
def data_upload(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('sistema/tasks/data_upload.html')
    else:
        form = DocumentForm()
    return render(request, 'sistema/tasks/data_upload.html', {
        'form': form
    })

#=======================================================================================================================
def read_files(request):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        # myfile = "media/documents/german_credit.csv"
        # df = pd.DataFrame()
        df = pd.read_csv(myfile, sep=",")
        data1 = df.iloc[1000:2136,2]
        plt.plot(data1, label='tempearatura')
        plt.title("Temperatura")
        plt.xlabel("Quantidade de Amostras")
        plt.ylabel("Temperatura em Graus Celsius")
        show1 = plt.show()
        data2 = df.iloc[1000:2136, 3]
        plt.plot(data2, label='umidade')
        plt.title("Umidade")
        plt.xlabel("Quantidade de Amostras")
        plt.ylabel("Umidade Relativa do Ar em %")
        show2 = plt.show()
        df = df.iloc[1000:2136,[0,1,2,3]]
        contexto = {
            'df': df.to_html(index=False),
            'show1': show1,
            'show2': show2,
        }
        return render(request, 'sistema/tasks/read_files.html', contexto)
    return render(request, 'sistema/tasks/read_files.html')

sistema/templates/sistema/base.html
<!DOCTYPE html>
<!-- template main of base -->
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="Trabalho de Conclusão de Curso da Graduação">
        <meta name="author" content="Marcelo Machado Pereira">

        <title>UV Friendly - DEV</title>
        <link rel="icon" href="{% static 'sistema/favicon.ico' %}" >

        <!-- Bootstrap core CSS-->
        <link href="{% static 'sistema/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

        <!-- Custom fonts for this template-->
        <link href="{% static 'sistema/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

        <!-- Page level plugin CSS-->
        <link href="{% static 'sistema/vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">

        <!-- Custom styles for this template-->
        <link href="{% static 'sistema/css/sb-admin.css' %}" rel="stylesheet">
    </head>

    <body id="page-top">
        <nav class="navbar navbar-expand navbar-dark bg-dark static-top">
            <a class="navbar-brand mr-1" href="{% url 'website:index' %}"><i class="far fa-sun"></i>&nbsp;UV Friendly</a>
            {% if user.is_anonymous %}
            <span style="margin-left:5%;color:white;">Olá Visitante!</span>
        </nav>
            <div class="container-fluid">
                <!-- Breadcrumbs-->
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <span>Ops! Você não está logado!</span>
                    </li>
                </ol>
                <ol>
                    <li class="breadcrumb-item active">Detectamos uma tentativa de Quebrar a Segurança;</li><br>
                    <li class="breadcrumb-item active">Não é possível acessar o Sistema diretamente pela URL;</li><br>
                    <li class="breadcrumb-item active">Por favor, clique em <a href="{% url 'login' %}">Login</a> para acessar o sistema;</li><br>
                    <li class="breadcrumb-item active">Se ainda não tem cadastro, por favor informe seus dados <a href="{% url 'accounts:register' %}">aqui.</a></li><br>
                    <li class="breadcrumb-item active">Iremos liberar o seu acesso em breve!</li><br>
                </ol>
                <hr>
                <span>Equipe de Suporte</span><br>
                <span>UV Friendly</span>
            </div>
                {% endif %}
                {% if user.is_authenticated %}
            <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
                <i class="fas fa-bars"></i>
            </button>
            <span style="margin-left:5%;color:white;">Olá {{ user.username }}!</span>
            <!-- Navbar Search -->
            <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <!--<div class="input-group">
            <input type="text" class="form-control" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
            <button class="btn btn-primary" type="button">
            <i class="fas fa-search"></i>
            </button>
            </div>
            </div>-->
            </form>

            <!-- Navbar -->
            <ul class="navbar-nav ml-auto ml-md-0">
                <li class="nav-item dropdown no-arrow mx-1">
                    <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-bell fa-fw"></i>
                        <span class="badge badge-danger">9+</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item dropdown no-arrow mx-1">
                    <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-envelope fa-fw"></i>
                        <span class="badge badge-danger">7</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item dropdown no-arrow">
                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-user-circle fa-fw"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                        <a class="dropdown-item" href="#">Settings</a>
                        <a class="dropdown-item" href="#">Activity Log</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
                    </div>
                </li>
            </ul>
        </nav>

        <div id="wrapper">

            <!-- Sidebar -->
            <ul class="sidebar navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'sistema:index' %}">
                        <i class="fas fa-fw fa-tachometer-alt"></i>
                        <span>Painel de Controle</span>
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="channelsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-tv"></i>
                        <span>Canais</span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="channelsDropdown">
                        <a class="dropdown-item" href="{% url 'sistema:channels' %}">Meus Canais</a>
                        <a class="dropdown-item" href="{% url 'sistema:watcheds' %}">Canais Monitorados</a>
                        <a class="dropdown-item" href="{% url 'sistema:publics' %}">Canais Públicos</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="tasksDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-tasks"></i>
                        <span>Tarefas</span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="tasksDropdown">
                        <a class="dropdown-item" href="{% url 'sistema:acquisition' %}">Aquisição</a>
                        <a class="dropdown-item" href="{% url 'sistema:synchronization' %}">Sincronização</a>
                        <a class="dropdown-item" href="{% url 'sistema:storage' %}">Armazenamento</a>
                        <a class="dropdown-item" href="{% url 'sistema:accessibility' %}">Acessibilidade</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-cogs"></i>
                        <span>Configurações</span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="pagesDropdown">
                        <a class="dropdown-item" href="{% url 'sistema:projects' %}">Projetos</a>
                        <a class="dropdown-item" href="{% url 'sistema:components' %}">Componentes</a>
                        <a class="dropdown-item" href="{% url 'sistema:technologies' %}">Tecnologias</a>
                        <a class="dropdown-item" href="{% url 'sistema:users' %}">Usuários</a>
                        <div class="dropdown-divider"></div>
                        <h6 class="dropdown-header">Other Pages:</h6>
                        <a class="dropdown-item" href="{% url 'sistema:error404' %}">404 Page</a>
                        <a class="dropdown-item" href="{% url 'sistema:blank' %}">Blank Page</a>
                    </div>
                </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'sistema:charts' %}">
                        <i class="fas fa-fw fa-chart-area"></i>
                        <span>Gráficos</span></a>
                    </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'sistema:tables' %}">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Tabelas</span></a>
                </li>
            </ul>

            <div id="content-wrapper">
                <div class="container-fluid">
                    <!-- Breadcrumbs-->
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="{% url 'sistema:index' %}">Painel de Controle</a>
                        </li>
                {% block content %}

                {% endblock %}
            </div>
            <!-- /.container-fluid -->

                <!-- Sticky Footer -->
                <footer class="sticky-footer">
                    <div class="container my-auto">
                        <div class="copyright text-center my-auto">
                            <span>Copyright © UV Friendly 2018</span>
                        </div>
                    </div>
                </footer>
            </div>
            <!-- /.content-wrapper -->
        </div>
        <!-- /#wrapper -->

        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top">
            <i class="fas fa-angle-up"></i>
        </a>

        <!-- Logout Modal-->
        <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Você deseja sair?</h5>
                            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">Selecione "Logout" abaixo se você estiver pronto para terminar sua sessão atual.</div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                        <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        <!-- Bootstrap core JavaScript-->
        <script src="{% static 'sistema/vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'sistema/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

        <!-- Core plugin JavaScript-->
        <script src="{% static 'sistema/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

        <!-- Page level plugin JavaScript-->
        <script src="{% static 'sistema/vendor/chart.js/Chart.min.js' %}"></script>

        <!-- Custom scripts for all pages-->
        <script src="{% static 'sistema/js/sb-admin.min.js' %}"></script>

        <!-- Demo scripts for this page-->
        <script src="{% static 'sistema/js/demo/chart-area-demo.js' %}"></script>
        <script src="{% static 'sistema/js/demo/chart-bar-demo.js' %}"></script>
        <script src="{% static 'sistema/js/demo/chart-pie-demo.js' %}"></script>
    </body>
</html>

sistema/templates/sistema/based.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="Trabalho de Conclusão de Curso da Graduação">
        <meta name="author" content="Marcelo Machado Pereira">

        <title>UV Friendly</title>
        <link rel="icon" href="{% static 'sistema/favicon.ico' %}">

        <!-- Bootstrap core CSS-->
        <link href="{% static 'sistema/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

        <!-- Custom fonts for this template-->
        <link href="{% static 'sistema/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

        <!-- Custom styles for this template-->
        <link href="{% static 'sistema/css/sb-admin.css' %}" rel="stylesheet">

    </head>

    <body class="bg-dark">
    <nav class="navbar navbar-expand navbar-dark bg-dark static-top">

        <a class="navbar-brand mr-1" href="{% url 'website:index' %}"><i class="far fa-sun"></i>&nbsp;UV Friendly</a>
        {% if user.is_authenticated %}
        <span style="margin-left:5%;color:white;">Olá {{ user.username }}!</span>
        {% else %}
        <span style="margin-left:5%;color:white;">Olá Visitante!</span>
        {% endif %}
    </nav>

    <div class="container">
        {% block content %}

        {% endblock %}
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'sistema/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'sistema/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'sistema/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    </body>
</html>

sistema/templates/sistema/blank.html
        {% extends 'sistema/base.html' %}

        {% block content %}
            <li class="breadcrumb-item active">Outras Páginas</li>
          </ol>

          <!-- Page Content -->
          <h1>Página em Branco</h1>
          <hr>
          <p>Este é um excelente ponto de partida para novas páginas personalizadas.</p>
        {% endblock %}

sistema/templates/sistema/charts.html
        {% extends 'sistema/base.html' %}

        {% block content %}
            <li class="breadcrumb-item active">Gráficos</li>
          </ol>

          <!-- Area Chart Example-->
          <div class="card mb-3">
            <div class="card-header">
              <i class="fas fa-chart-area"></i>
              Area Chart Example</div>
            <div class="card-body">
              <canvas id="myAreaChart" width="100%" height="30"></canvas>
            </div>
            <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
          </div>

          <div class="row">
            <div class="col-lg-8">
              <div class="card mb-3">
                <div class="card-header">
                  <i class="fas fa-chart-bar"></i>
                  Bar Chart Example</div>
                <div class="card-body">
                  <canvas id="myBarChart" width="100%" height="50"></canvas>
                </div>
                <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
              </div>
            </div>
            <div class="col-lg-4">
              <div class="card mb-3">
                <div class="card-header">
                  <i class="fas fa-chart-pie"></i>
                  Pie Chart Example</div>
                <div class="card-body">
                  <canvas id="myPieChart" width="100%" height="100"></canvas>
                </div>
                <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
              </div>
            </div>
          </div>

          <p class="small text-center text-muted my-5">
            <em>More chart examples coming soon...</em>
          </p>
        {% endblock %}

sistema/templates/sistema/error404.html
        {% extends 'sistema/base.html' %}

        {% block content %}
            <li class="breadcrumb-item active">404 Error</li>
          </ol>

          <!-- Page Content -->
          <h1 class="display-1">404</h1>
          <p class="lead">Página não encontrada. Você pode
            <a href="javascript:history.back()">voltar </a>
            para a página anterior ou voltar para
            <a href="{% url 'sistema:index' %}">página principal</a>.</p>
        {% endblock %}

sistema/templates/sistema/index.html
        {% extends 'sistema/base.html' %}
        <!-- template main of index -->
        {% block content %}
                <li class="breadcrumb-item active">Visão Geral</li>
            </ol>

            <!-- Icon Cards-->
            <div class="row">
                <div class="col-xl-3 col-sm-6 mb-3">
                    <div class="card text-white bg-primary o-hidden h-100">
                        <div class="card-body">
                            <div class="card-body-icon">
                                <i class="fas fa-sign-in-alt"></i>
                            </div>
                            <div class="mr-5">Últimos Acessos</div>
                        </div>
                        <a class="card-footer text-white clearfix small z-1" href="#">
                            <span class="float-left">Veja Detalhes</span>
                            <span class="float-right">
                            <i class="fas fa-angle-right"></i>
                          </span>
                        </a>
                    </div>
                </div>
                <div class="col-xl-3 col-sm-6 mb-3">
                    <div class="card text-white bg-warning o-hidden h-100">
                        <div class="card-body">
                            <div class="card-body-icon">
                                <i class="fas fa-tv"></i>
                            </div>
                            <div class="mr-5">Info dos Canais</div>
                        </div>
                        <a class="card-footer text-white clearfix small z-1" href="#">
                            <span class="float-left">Veja Detalhes</span>
                            <span class="float-right">
                            <i class="fas fa-angle-right"></i>
                          </span>
                        </a>
                    </div>
                </div>
                <div class="col-xl-3 col-sm-6 mb-3">
                    <div class="card text-white bg-success o-hidden h-100">
                        <div class="card-body">
                            <div class="card-body-icon">
                                <i class="fas fa-tasks"></i>
                            </div>
                            <div class="mr-5">Info das Tarefas</div>
                        </div>
                        <a class="card-footer text-white clearfix small z-1" href="#">
                            <span class="float-left">Veja Detalhes</span>
                            <span class="float-right">
                            <i class="fas fa-angle-right"></i>
                          </span>
                        </a>
                    </div>
                </div>
                <div class="col-xl-3 col-sm-6 mb-3">
                    <div class="card text-white bg-danger o-hidden h-100">
                        <div class="card-body">
                            <div class="card-body-icon">
                                <i class="fas fa-cogs"></i>
                            </div>
                            <div class="mr-5">Últimas Configurações</div>
                        </div>
                        <a class="card-footer text-white clearfix small z-1" href="#">
                            <span class="float-left">Veja Detalhes</span>
                            <span class="float-right">
                            <i class="fas fa-angle-right"></i>
                          </span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xl-3 col-sm-6 mb-3" id="detalhes-acessos" style="display:block;">
                    <div class="card o-hidden h-100">
                        <div class="card-body">
                            <div class="mr-5">Últimos Acessos</div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-sm-6 mb-3" id="detalhes-canais" style="display:block;">
                    <div class="card o-hidden h-100">
                        <div class="card-body">
                            <div class="mr-5">Info dos Canais</div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-sm-6 mb-3" id="detalhes-tarefas" style="display:block;">
                    <div class="card o-hidden h-100">
                        <div class="card-body">
                            <div class="mr-5">Info das Tarefas</div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-sm-6 mb-3" id="detalhes-config" style="display:block;">
                    <div class="card o-hidden h-100">
                        <div class="card-body">
                            <div class="mr-5">Últimas Configurações</div>
                        </div>
                    </div>
                </div>
            </div>
        {% endblock %}