crud/urls.py
from . import views
from django.conf.urls import url
from django.urls import path

app_name = 'crud'

urlpatterns = [
    # Create a new register
    url(r'newp/', views.ProjetosCreate.as_view(), name='form_projs'),
    url(r'newc/', views.ComponentesCreate.as_view(), name='form_comps'),
    url(r'newt/', views.TecnologiasCreate.as_view(), name='form_techs'),
    url(r'newu/', views.UsuariosCreate.as_view(), name='form_users'),

    # Update an existent register
    path(r'editp/<int:pk>', views.ProjetosUpdate.as_view(), name='form_projs'),
    path(r'editc/<int:pk>', views.ComponentesUpdate.as_view(), name='form_comps'),
    path(r'editt/<int:pk>', views.TecnologiasUpdate.as_view(), name='form_techs'),
    path(r'editu/<int:pk>', views.UsuariosUpdate.as_view(), name='form_users'),

    # Delete an existent register
    path(r'delep/<int:pk>', views.ProjetosDelete.as_view(), name='dele_projs'),
    path(r'delec/<int:pk>', views.ComponentesDelete.as_view(), name='dele_comps'),
    path(r'delet/<int:pk>', views.TecnologiasDelete.as_view(), name='dele_techs'),
    path(r'deleu/<int:pk>', views.UsuariosDelete.as_view(), name='dele_users'),

    # Detail of an existent register
    path(r'viewp/<int:pk>', views.ProjetosView.as_view(), name='view_projs'),
    path(r'viewc/<int:pk>', views.ComponentesView.as_view(), name='view_comps'),
    path(r'viewt/<int:pk>', views.TecnologiasView.as_view(), name='view_techs'),
    path(r'viewu/<int:pk>', views.UsuariosView.as_view(), name='view_users'),
]

sistema/urls.py
from . import views
from django.conf.urls import url

app_name = 'sistema'

urlpatterns = [
    url(r'base', views.base, name='base'),
    url(r'based/', views.based, name='based'),
    url(r'blank/', views.blank, name='blank'),
    url(r'charts/', views.charts, name='charts'),
    url(r'error404/', views.error404, name='error404'),
    url(r'^$', views.index, name='index'),
    url(r'tables/', views.tables, name='tables'),

    url(r'channels/', views.channels, name='channels'),
    url(r'publics/', views.publics, name='publics'),
    url(r'watcheds/', views.watcheds, name='watcheds'),

    url(r'accessibility/', views.accessibility, name='accessibility'),
    url(r'acquisition/', views.acquisition, name='acquisition'),
    url(r'file_upload/', views.file_upload, name='file_upload'),
    url(r'data_upload/', views.data_upload, name='data_upload'),
    url(r'read_files/', views.read_files, name='read_files'),
    url(r'storage/', views.storage, name='storage'),
    url(r'synchronization/', views.synchronization, name='synchronization'),

    url(r'components/', views.components, name='components'),
    url(r'projects/', views.projects, name='projects'),
    url(r'technologies/', views.technologies, name='technologies'),
    url(r'users/', views.users, name='users'),
]

uvfriendly/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Interface administrativa
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),


    # URL padrão
    path('', include('website.urls', namespace='website')),
    path('sistema/', include('sistema.urls', namespace='sistema')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('crud/', include('crud.urls', namespace='crud')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sistema/views.py
from django.core.files.storage import FileSystemStorage
from django.shortcuts import render, redirect
from matplotlib import pyplot as plt
import pandas as pd

from uvfriendly.models import Componentes, Projetos, Tecnologias, Usuarios
from uvfriendly.forms import DocumentForm

template_name = 'sistema'

# Create your views here.
def base(request):
    return render(request, 'sistema/base.html')


def based(request):
    return render(request, 'sistema/based.html')


def blank(request):
    return render(request, 'sistema/blank.html')


def charts(request):
    return render(request, 'sistema/charts.html')


def error404(request):
    return render(request, 'sistema/error404.html')


def index(request):
    return render(request, 'sistema/index.html')


def tables(request):
    tabela = pd.read_csv("media/documents/german_credit.csv")
    contexto = {
        'tabela': tabela.to_html(index=False)
    }
    return render(request, 'sistema/tables.html', contexto)

#====================================================

# Channels ===================================================
def channels(request):
    return render(request, 'sistema/channels/channels.html')


def publics(request):
    return render(request, 'sistema/channels/publics.html')


def watcheds(request):
    return render(request, 'sistema/channels/watcheds.html')

#=============================================================

# Tasks ==========================================================
def accessibility(request):
    return render(request, 'sistema/tasks/accessibility.html')


def acquisition(request):
    return render(request, 'sistema/tasks/acquisition.html')


def storage(request):
    return render(request, 'sistema/tasks/storage.html')


def synchronization(request):
    return render(request, 'sistema/tasks/synchronization.html')

#=================================================================

# Tools ===================================================================================
def components(request):
    componentes = Componentes.objetos.all()
    contexto = {
        'componentes': componentes
    }
    return render(request, 'sistema/tools/components.html', contexto)

#__________________________________________________________________________________________
def projects(request):
    projetos = Projetos.objetos.all()
    contexto = {
        'projetos': projetos
    }
    return render(request, 'sistema/tools/projects.html', contexto)

#_______________________________________________________________________________________________________________________
def technologies(request):
    tecnologias = Tecnologias.objetos.all()
    contexto = {
        'tecnologias': tecnologias
    }
    return render(request, 'sistema/tools/technologies.html', contexto)

#_______________________________________________________________________________________________________________________
def users(request):
    usuarios = Usuarios.objetos.all()
    contexto = {
        'usuarios':usuarios
    }
    return render(request, 'sistema/tools/users.html', contexto)

#=======================================================================================================================
def file_upload(request):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)
        return render(request, 'sistema/tasks/file_upload.html',{
            'uploaded_file_url': uploaded_file_url
        })
    return render(request, 'sistema/tasks/file_upload.html')

#=======================================================================================================================
def data_upload(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('sistema/tasks/data_upload.html')
    else:
        form = DocumentForm()
    return render(request, 'sistema/tasks/data_upload.html', {
        'form': form
    })

#=======================================================================================================================
def read_files(request):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        # myfile = "media/documents/german_credit.csv"
        # df = pd.DataFrame()
        df = pd.read_csv(myfile, sep=",")
        data1 = df.iloc[1000:2136,2]
        plt.plot(data1, label='tempearatura')
        plt.title("Temperatura")
        plt.xlabel("Quantidade de Amostras")
        plt.ylabel("Temperatura em Graus Celsius")
        show1 = plt.show()
        data2 = df.iloc[1000:2136, 3]
        plt.plot(data2, label='umidade')
        plt.title("Umidade")
        plt.xlabel("Quantidade de Amostras")
        plt.ylabel("Umidade Relativa do Ar em %")
        show2 = plt.show()
        df = df.iloc[1000:2136,[0,1,2,3]]
        contexto = {
            'df': df.to_html(index=False),
            'show1': show1,
            'show2': show2,
        }
        return render(request, 'sistema/tasks/read_files.html', contexto)
    return render(request, 'sistema/tasks/read_files.html')

sistema/templates/sistema/tools/components.html
        {% extends 'sistema/base.html' %}
        <!-- template main of components -->
        {% block content %}
                <li class="breadcrumb-item">Configurações</li>
            </ol>
            <!-- Page Content -->
            <div class="card-header mb-3">
                <a class="btn btn-primary js-scroll-trigger" href="{% url 'crud:form_comps' %}">
                    <i class="fas fa-plus"></i>
                </a>&nbsp;&nbsp;Componentes
            </div>
            <div class="card card-box">
                <table class="table-bordered">
                    <tr align="center" bgcolor="#e8ebee">
                        <td><strong>NOME</strong></td><td><strong>DESCRIÇÃO</strong></td><td><strong>FULLSIZE</strong></td><td><strong>THUMBNAILS</strong></td><td><strong>STATUS</strong></td><td><strong>AÇÕES</strong></td>
                    </tr>
                    {% for comp in componentes %}
                    <tr align="center">
                        <td>{{ comp.nome }}</td>
                        <td>{{ comp.descricao }}</td>
                        <td>{{ comp.fullsize }}</td>
                        <td>{{ comp.thumbnails }}</td>
                        <td>{{ comp.status }}</td>
                        <td>
                            <a class="btn js-scroll-trigger" href="{% url 'crud:form_comps' comp.id %}"><i class="fas fa-edit"></i></a>
                            <a class="btn js-scroll-trigger" href="{% url 'crud:dele_comps' comp.id %}"><i class="fas fa-trash-alt"></i></a>
                            <a class="btn js-scroll-trigger" href="{% url 'crud:view_comps' comp.id %}"><i class="fas fa-search"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        {% endblock %}

sistema/templates/sistema/tools/projects.html
        {% extends 'sistema/base.html' %}
        <!-- template main of projects -->
        {% block content %}
                <li class="breadcrumb-item">Configurações</li>
            </ol>
            <!-- Page Content -->
            <div class="card-header mb-3">
                <a class="btn btn-primary js-scroll-trigger" href="{% url 'crud:form_projs' %}">
                    <i class="fas fa-plus"></i>
                </a>&nbsp;&nbsp;Projetos
            </div>
            <div class="card card-box">
                <table class="table-bordered">
                    <tr align="center" bgcolor="#e8ebee">
                        <td><strong>NOME</strong></td><td><strong>DESCRIÇÃO</strong></td><td><strong>CLASSE</strong></td><td><strong>STATUS</strong></td><td><strong>AÇÕES</strong></td>
                    </tr>
                    {% for proj in projetos %}
                    <tr align="center">
                        <td>{{ proj.nome }}</td>
                        <td>{{ proj.descricao }}</td>
                        <td>{{ proj.classe }}</td>
                        <td>{{ proj.status }}</td>
                        <td>
                            <a class="btn js-scroll-trigger" href="{% url 'crud:form_projs' proj.id %}"><i class="fas fa-edit"></i></a>
                            <a class="btn js-scroll-trigger" href="{% url 'crud:dele_projs' proj.id %}"><i class="fas fa-trash-alt"></i></a>
                            <a class="btn js-scroll-trigger" href="{% url 'crud:view_projs' proj.id %}"><i class="fas fa-search"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        {% endblock %}

sistema/templates/sistema/tools/technologies.html
        {% extends 'sistema/base.html' %}
        <!-- template main of technologies -->
        {% block content %}
                <li class="breadcrumb-item">Configurações</li>
            </ol>
            <!-- Page Content -->
            <div class="card-header mb-3">
                <a class="btn btn-primary js-scroll-trigger" href="{% url 'crud:form_techs' %}">
                    <i class="fas fa-plus"></i>
                </a>&nbsp;&nbsp;Tecnologias
            </div>
            <div class="card card-box">
                <table class="table-bordered">
                    <tr align="center" bgcolor="#e8ebee">
                        <td><strong>NOME</strong></td><td><strong>CLASSE</strong></td><td><strong>ALT</strong></td><td><strong>STATUS</strong></td><td><strong>AÇÕES</strong></td>
                    </tr>
                    {% for tech in tecnologias %}
                    <tr align="center">
                        <td>{{ tech.nome }}</td>
                        <td>{{ tech.classe }}</td>
                        <td>{{ tech.alt }}</td>
                        <td>{{ tech.status }}</td>
                        <td>
                            <a class="btn js-scroll-trigger" href="{% url 'crud:form_techs' tech.id %}"><i class="fas fa-edit"></i></a>
                            <a class="btn js-scroll-trigger" href="{% url 'crud:dele_techs' tech.id %}"><i class="fas fa-trash-alt"></i></a>
                            <a class="btn js-scroll-trigger" href="{% url 'crud:view_techs' tech.id %}"><i class="fas fa-search"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        {% endblock %}

sistema/templates/sistema/tools/users.html
        {% extends 'sistema/base.html' %}
        <!-- template main of users -->
        {% block content %}
                <li class="breadcrumb-item">Configurações</li>
            </ol>
            <!-- Page Content -->
            <div class="card-header mb-3">
                <a class="btn btn-primary js-scroll-trigger" href="{% url 'crud:form_users' %}">
                    <i class="fas fa-plus"></i>
                </a>&nbsp;&nbsp;Usuários
            </div>
            <div class="card card-box">
                <table class="table-bordered">
                    <tr align="center" bgcolor="#e8ebee">
                        <td><strong>CPF</strong></td><td><strong>NOME</strong></td><td><strong>SOBRENOME</strong></td><td><strong>EMAIL</strong></td><td><strong>SENHA1</strong></td><td><strong>SENHA2</strong></td><td><strong>STATUS</strong></td><td><strong>LEVEL</strong></td><td><strong>AÇÕES</strong></td>
                    </tr>
                    {% for user in usuarios %}
                    <tr align="center">
                        <td>{{ user.cpf }}</td>
                        <td>{{ user.nome }}</td>
                        <td>{{ user.sobrenome }}</td>
                        <td>{{ user.email }}</td>
                        <td>{{ user.senha1 }}</td>
                        <td>{{ user.senha2 }}</td>
                        <td>{{ user.status }}</td>
                        <td>{{ user.level }}</td>
                        <td>
                            <a class="btn js-scroll-trigger" href="{% url 'crud:form_users' user.id %}"><i class="fas fa-edit"></i></a>
                            <a class="btn js-scroll-trigger" href="{% url 'crud:dele_users' user.id %}"><i class="fas fa-trash-alt"></i></a>
                            <a class="btn js-scroll-trigger" href="{% url 'crud:view_users' user.id %}"><i class="fas fa-search"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        {% endblock %}