accounts/urls.py
from . import views
from django.conf.urls import url

app_name = 'accounts'

urlpatterns = [
    url(r'login/', views.login, name='login'),
    url(r'register/', views.SignUp.as_view(), name='register'),
    url(r'forgot_password/', views.forgot_password, name='forgot_password'),
]

crud/urls.py
from . import views
from django.conf.urls import url
from django.urls import path

app_name = 'crud'

urlpatterns = [
    # Create a new register
    url(r'newp/', views.ProjetosCreate.as_view(), name='form_projs'),
    url(r'newc/', views.ComponentesCreate.as_view(), name='form_comps'),
    url(r'newt/', views.TecnologiasCreate.as_view(), name='form_techs'),
    url(r'newu/', views.UsuariosCreate.as_view(), name='form_users'),

    # Update an existent register
    path(r'editp/<int:pk>', views.ProjetosUpdate.as_view(), name='form_projs'),
    path(r'editc/<int:pk>', views.ComponentesUpdate.as_view(), name='form_comps'),
    path(r'editt/<int:pk>', views.TecnologiasUpdate.as_view(), name='form_techs'),
    path(r'editu/<int:pk>', views.UsuariosUpdate.as_view(), name='form_users'),

    # Delete an existent register
    path(r'delep/<int:pk>', views.ProjetosDelete.as_view(), name='dele_projs'),
    path(r'delec/<int:pk>', views.ComponentesDelete.as_view(), name='dele_comps'),
    path(r'delet/<int:pk>', views.TecnologiasDelete.as_view(), name='dele_techs'),
    path(r'deleu/<int:pk>', views.UsuariosDelete.as_view(), name='dele_users'),

    # Detail of an existent register
    path(r'viewp/<int:pk>', views.ProjetosView.as_view(), name='view_projs'),
    path(r'viewc/<int:pk>', views.ComponentesView.as_view(), name='view_comps'),
    path(r'viewt/<int:pk>', views.TecnologiasView.as_view(), name='view_techs'),
    path(r'viewu/<int:pk>', views.UsuariosView.as_view(), name='view_users'),
]

sistema/urls.py
from . import views
from django.conf.urls import url

app_name = 'sistema'

urlpatterns = [
    url(r'base', views.base, name='base'),
    url(r'based/', views.based, name='based'),
    url(r'blank/', views.blank, name='blank'),
    url(r'charts/', views.charts, name='charts'),
    url(r'error404/', views.error404, name='error404'),
    url(r'^$', views.index, name='index'),
    url(r'tables/', views.tables, name='tables'),

    url(r'channels/', views.channels, name='channels'),
    url(r'publics/', views.publics, name='publics'),
    url(r'watcheds/', views.watcheds, name='watcheds'),

    url(r'accessibility/', views.accessibility, name='accessibility'),
    url(r'acquisition/', views.acquisition, name='acquisition'),
    url(r'file_upload/', views.file_upload, name='file_upload'),
    url(r'data_upload/', views.data_upload, name='data_upload'),
    url(r'read_files/', views.read_files, name='read_files'),
    url(r'storage/', views.storage, name='storage'),
    url(r'synchronization/', views.synchronization, name='synchronization'),

    url(r'components/', views.components, name='components'),
    url(r'projects/', views.projects, name='projects'),
    url(r'technologies/', views.technologies, name='technologies'),
    url(r'users/', views.users, name='users'),
]

uvfriendly/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Interface administrativa
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),


    # URL padrão
    path('', include('website.urls', namespace='website')),
    path('sistema/', include('sistema.urls', namespace='sistema')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('crud/', include('crud.urls', namespace='crud')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

uvfriendly/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Document(models.Model):
    description = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to='documents/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    objetos = models.Manager()



class Componentes(models.Model):
    nome = models.CharField(
        max_length=50, null=False, blank=False)
    descricao = models.CharField(
        max_length=150, null=False, blank=False)
    fullsize = models.CharField(
        max_length=255, null=False, blank=False)
    thumbnails = models.CharField(
        max_length=255, null=False, blank=False)
    status = models.IntegerField(
        null=False, blank=False, default=0)

    objetos = models.Manager()


class Projetos(models.Model):
    nome = models.CharField(
        max_length=20, null=False, blank=False)
    descricao = models.CharField(
        max_length=255, null=False, blank=False)
    classe = models.CharField(
        max_length=255, null=False, blank=False, default='')
    status = models.IntegerField(
        null=False, blank=False, default=0)

    objetos = models.Manager()


class Tecnologias(models.Model):
    classe = models.CharField(
        max_length=150, null=False, blank=False)
    alt = models.CharField(
        max_length=50, null=False, blank=False)
    nome = models.CharField(
        max_length=50, null=False, blank=False)
    status = models.IntegerField(
        null=False, blank=False, default=0)

    objetos = models.Manager()


class Usuarios(models.Model):
    cpf = models.CharField(
        max_length=14, null=False, blank=False)
    nome = models.CharField(
        max_length=255, null=False, blank=False)
    sobrenome = models.CharField(
        max_length=255, null=False, blank=False)
    email = models.EmailField(
        max_length=255, null=False, blank=False)
    senha1 = models.CharField(
        max_length=255, null=False, blank=False)
    senha2 = models.CharField(
        max_length=255, null=False, blank=False)
    status = models.IntegerField(
        default=0, null=False, blank=False)
    level = models.IntegerField(
        default=0, null=False, blank=False)

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse('form_users', kwargs={'pk':self.pk})

    objetos = models.Manager()


class Canais(models.Model):
    nome = models.ForeignKey(Usuarios, on_delete=models.CASCADE)
    nomecanal = models.CharField(
        max_length=50, null=False, blank=False)
    descricao = models.CharField(
        max_length=150, null=False, blank=False)
    campo_01 = models.CharField(
        max_length=50, null=True, blank=True)
    campo_02 = models.CharField(
        max_length=50, null=True, blank=True)
    campo_03 = models.CharField(
        max_length=50, null=True, blank=True)
    campo_04 = models.CharField(
        max_length=50, null=True, blank=True)
    campo_05 = models.CharField(
        max_length=50, null=True, blank=True)
    campo_06 = models.CharField(
        max_length=50, null=True, blank=True)
    campo_07 = models.CharField(
        max_length=50, null=True, blank=True)
    campo_08 = models.CharField(
        max_length=50, null=True, blank=True)
    metadata = models.CharField(
        max_length=255, null=False, blank=False)
    tags = models.CharField(
        max_length=255, null=False, blank=False)
    latitude = models.IntegerField(
        null=True, blank=True, default=0)
    longitude = models.IntegerField(
        null=True, blank=True, default=0)
    elevation = models.IntegerField(
        null=True, blank=True, default=0)
    status = models.IntegerField(
        null=True, blank=True, default=0)

    objetos = models.Manager()

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import render

template_name = 'accounts'

def forgot_password(request):
    return render(request, 'forgot-password.html')

def login(request):
    return render(request, 'login.html')


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'register.html'

accounts/templates/forgot-password.html
        {% extends 'sistema/based.html' %}

        {% block content %}
        <div class="card card-login mx-auto mt-5">
            <div class="card-header">Redefinir a Senha</div>
            <div class="card-body">
                <div class="text-center mb-4">
                    <h4>Esqueceu a Senha?</h4>
                    <p>Informe seu endereço de email e iremos enviar para você as instruções de como redefinir sua senha.</p>
                </div>
                <form>
                    <div class="form-group">
                        <div class="form-label-group">
                            <label for="inputEmail">Informe o Endereço de Email</label>
                            <input type="email" id="inputEmail" class="form-control" placeholder="Enter email address" required="required" autofocus="autofocus">
                        </div>
                    </div>
                    <a class="btn btn-primary btn-block" href="{% url 'accounts:login' %}">Redefinir a Senha</a>
                </form>
                <div class="text-center">
                    <a class="d-block small mt-3" href="{% url 'accounts:register' %}">Cadastrar uma Conta</a>
                    <a class="d-block small" href="{% url 'accounts:login' %}">Página de Login</a>
                    <a class="d-block small" href="{% url 'website:index' %}">Voltar para o Site</a>
                </div>
            </div>
        </div>
        {% endblock %}

accounts/templates/register.html
        {% extends 'sistema/based.html' %}

        {% block content %}
        <div class="card card-register mx-auto mt-5">
            <div class="card-header">Conta de Usuário</div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-6">
                                <div class="">
                                    <label for="id_username">Usuário</label>
                                    <input type="text" name="username" id="id_username" class="form-control" placeholder="Informe o Usuário" required="required" autofocus="autofocus">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="">
                                    <label for="id_last_name">Sobrenome</label>
                                    <input type="text" name="last_name" id="id_last_name" class="form-control" placeholder="Informe o Sobrenome" required="required">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="">
                            <label for="id_email">Endereço de Email</label>
                            <input type="email" name="email" id="id_email" class="form-control" placeholder="Informe o Email" required="required">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-6">
                                <div class="">
                                    <label for="id_password1">Senha</label>
                                    <input type="password" name="password1" id="id_password1" class="form-control" placeholder="Digite a Senha" required="required">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="">
                                    <label for="id_password2">Confirmar Senha</label>
                                    <input type="password" name="password2" id="id_password2" class="form-control" placeholder="Confirme a Senha" required="required">
                                </div>
                            </div>
                        </div>
                    </div>
                    {% if user.is_authenticated %}
                    <a class="btn btn-primary btn-block" href="{% url 'sistema:index' %}">Você já é Cadastrado</a>
                    {% else %}
                    <button class="btn btn-primary btn-block js-scroll-trigger" type="submit">Cadastrar</button>
                    {% endif %}
                </form>
                <div class="text-center">
                    <a class="d-block small mt-3" href="{% url 'accounts:login' %}">Página de Login</a>
                    <a class="d-block small" href="{% url 'accounts:forgot_password' %}">Esqueceu sua Senha?</a>
                    <a class="d-block small" href="{% url 'website:index' %}">Voltar para o Site</a>
                </div>
            </div>
        </div>
        {% endblock %}